# Generated by Django 5.0.13 on 2025-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_officehours11'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeimprovementrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
