# Generated by Django 5.0.13 on 2025-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userregisterstu'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeimprovementrequest',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
