# Generated by Django 5.0.13 on 2025-04-12 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gradeimprovementrequest_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregisterstu')),
            ],
        ),
    ]
