# Generated by Django 5.0.13 on 2025-04-12 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userregisterstu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterstu',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
