# Generated by Django 5.0.13 on 2025-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterstu',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
