# Generated by Django 5.0.13 on 2025-04-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userregisterstu_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterstu',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
