# Generated by Django 5.0.13 on 2025-04-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userregisterstu_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterstu',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
