# Generated by Django 5.0.13 on 2025-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_userregisterstu_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterstu',
            name='user',
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userregisterstu',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
