# Generated by Django 5.0.13 on 2025-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_userregisterstu_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterstu',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
