# Generated by Django 5.0.13 on 2025-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userregisterstu1_alter_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregisterstu1',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
